spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://192.168.24.77:5432/huii-pro
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      host: 192.168.24.77
      port: 6379
      database: 0
      password:
      connect-timeout: 60000
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          max-active: 20
          max-wait: 100000

oss:
  endpoint: 192.168.24.101:9001
  bucketName: local
  accessKey: minio
  secretKey: admin123
  https: false
  access-policy: 1
  access-url: https://admin.huii147.xyz/ofs1
local:
  base-path: D:/huii/file
  endPoint: http://127.0.0.1:8080/oss/local

mail:
  enable-mail: true
  port: 25
  protocol: smtp
  host: smtp.163.com
  username: H1740268plw32e@163.com
  password: SBOHNTSFXQUDIELY