spring:
  datasource:
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    #多数据源配置
    #https://www.kancloud.cn/tracy5546/dynamic-datasource/2264611
    dynamic:
      primary: master
      strict: false
      datasource:
        #主数据库
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.24.77:5432/huii-reboot
          username: root
          password: root
          #type: com.zaxxer.hikari.HikariDataSource
          #driver-class-name: com.mysql.cj.jdbc.Driver
          #url: jdbc:mysql://192.168.24.77:3306/huii-reboot?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          #username: root
          #password: root
          #从数据库
        slave:
          lazy: true
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.24.77:5432/huii-reboot
          username: root
          password: root
          #type: com.zaxxer.hikari.HikariDataSource
          # driver-class-name: com.mysql.cj.jdbc.Driver
          #url: jdbc:mysql://192.168.24.77:3306/huii-reboot?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          #username: root
          #password: root
  data:
    redis:
      host: 192.168.24.77
      port: 6379
      database: 0
      password:
      connect-timeout: 60000
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          max-active: 20
          max-wait: 100000

#文件服务配置
oss:
  endpoint: 192.168.24.101:9001
  bucketName: local
  accessKey: minio
  secretKey: admin123
  https: false
  accessPolicy: 1
  #直接访问地址
  #需要通过nginx转发到minio
  access-url: http://127.0.0.1:8080/ofs1
local:
  #接口访问地址
  endPoint: http://127.0.0.1:8080/oss/local
  #本地文件存储路径
  #docker路径
  #basePath: /huii/data
  #本地路径
  basePath: D:/huii/file

#邮箱服务配置
mail:
  enable-mail: true
  port: 25
  protocol: smtp
  host: smtp.163.com
  username: H1740268plw32e@163.com
  password: SBOHNTSFXQUDIELY