spring:
  datasource:
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    #多数据源配置
    #https://www.kancloud.cn/tracy5546/dynamic-datasource/2264611
    dynamic:
      primary: master
      strict: false
      datasource:
        #主数据库
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:postgresql://192.168.24.77:5432/huii-pro
          username: root
          password: root
          driver-class-name: org.postgresql.Driver
        #从数据库
        slave:
          lazy: true
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:postgresql://192.168.24.77:5432/huii-pro
          username: root
          password: root
          driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.24.77
      port: 6379
      database: 0
      password:
      connect-timeout: 60000
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          max-active: 20
          max-wait: 100000

#文件服务配置
oss:
  endpoint: 192.168.24.101:9001
  bucketName: local
  accessKey: minio
  secretKey: admin123
  https: false
  access-policy: 1
  #域名访问链接，需自行配置替换
  access-url: https://admin.huii147.xyz/ofs1
local:
  endPoint: http://127.0.0.1:8080/oss/local
  base-path: D:/huii/file

#邮箱服务配置
mail:
  enable-mail: true
  port: 25
  protocol: smtp
  host: smtp.163.com
  username: H1740268plw32e@163.com
  password: SBOHNTSFXQUDIELY